#!/bin/bash
#
# Hytale Server Setup Script
# For use on hosting with Java 25 already installed
#
# Usage: ./setup-hytale-server.sh
#

set -e  # Exit on error

echo "========================================="
echo "  Hytale Server Setup Script"
echo "========================================="
echo ""

# Configuration
read -p "Enter server directory path (e.g., /home/minecraft/hytale): " SERVER_DIR
read -p "Enter server port (default 5520): " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-5520}

read -p "Enter minimum RAM (e.g., 4G): " MIN_RAM
MIN_RAM=${MIN_RAM:-4G}

read -p "Enter maximum RAM (e.g., 8G): " MAX_RAM
MAX_RAM=${MAX_RAM:-8G}

echo ""
echo "Configuration:"
echo "  Directory: $SERVER_DIR"
echo "  Port: $SERVER_PORT"
echo "  RAM: $MIN_RAM - $MAX_RAM"
echo ""
read -p "Proceed? (y/n): " CONFIRM

if [ "$CONFIRM" != "y" ]; then
    echo "Aborted."
    exit 1
fi

# Create directory structure
echo ""
echo "[1/7] Creating directory structure..."
mkdir -p "$SERVER_DIR"
cd "$SERVER_DIR"
mkdir -p mods logs .cache backups

# Check Java version
echo ""
echo "[2/7] Checking Java version..."
JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d'.' -f1)

if [ "$JAVA_VERSION" -ne 25 ]; then
    echo "ERROR: Java 25 is required. Found Java $JAVA_VERSION"
    echo "Please install Java 25 from Adoptium: https://adoptium.net/"
    exit 1
fi

echo "✓ Java 25 detected"

# Download Hytale server files
echo ""
echo "[3/7] Downloading Hytale server files..."
echo "Choose download method:"
echo "  1) Hytale Downloader CLI (Recommended)"
echo "  2) Manual (I'll copy files myself)"
read -p "Choice (1/2): " DOWNLOAD_METHOD

if [ "$DOWNLOAD_METHOD" = "1" ]; then
    echo "Downloading Hytale Downloader..."

    if command -v wget &> /dev/null; then
        wget -O hytale-downloader.zip https://hytale.com/downloads/hytale-downloader.zip
    elif command -v curl &> /dev/null; then
        curl -L -o hytale-downloader.zip https://hytale.com/downloads/hytale-downloader.zip
    else
        echo "ERROR: Neither wget nor curl found. Please install one."
        exit 1
    fi

    echo "Extracting downloader..."
    unzip -q hytale-downloader.zip
    chmod +x hytale-downloader

    echo "Downloading Hytale server and assets..."
    ./hytale-downloader

    if [ -f "game.zip" ]; then
        echo "Extracting server files..."
        unzip -q game.zip
        echo "✓ Server files downloaded"
    else
        echo "ERROR: Download failed"
        exit 1
    fi
else
    echo ""
    echo "Manual setup selected."
    echo "Please copy the following to $SERVER_DIR:"
    echo "  - Server/ folder"
    echo "  - Assets.zip"
    echo ""
    read -p "Press Enter when files are copied..."

    if [ ! -d "Server" ] || [ ! -f "Assets.zip" ]; then
        echo "ERROR: Server/ or Assets.zip not found!"
        exit 1
    fi

    echo "✓ Server files detected"
fi

# Configure firewall
echo ""
echo "[4/7] Configuring firewall..."

if command -v ufw &> /dev/null; then
    echo "Detected ufw firewall"
    sudo ufw allow $SERVER_PORT/udp
    echo "✓ UDP port $SERVER_PORT opened"
elif command -v iptables &> /dev/null; then
    echo "Detected iptables firewall"
    sudo iptables -A INPUT -p udp --dport $SERVER_PORT -j ACCEPT
    sudo iptables-save > /etc/iptables/rules.v4 2>/dev/null || true
    echo "✓ UDP port $SERVER_PORT opened"
else
    echo "⚠ No firewall detected. Please manually open UDP port $SERVER_PORT"
fi

# Create startup script
echo ""
echo "[5/7] Creating startup script..."

cat > start.sh << 'EOFSTART'
#!/bin/bash

# Hytale Server Startup Script
# Auto-generated by setup script

# Configuration
SERVER_JAR="Server/HytaleServer.jar"
ASSETS_PATH="Assets.zip"
PORT=__PORT__
MIN_RAM=__MIN_RAM__
MAX_RAM=__MAX_RAM__

# Java arguments (Aikar's flags optimized for Hytale)
JAVA_ARGS="-Xms${MIN_RAM} -Xmx${MAX_RAM}"
JAVA_ARGS="$JAVA_ARGS -XX:+UseG1GC"
JAVA_ARGS="$JAVA_ARGS -XX:+ParallelRefProcEnabled"
JAVA_ARGS="$JAVA_ARGS -XX:MaxGCPauseMillis=200"
JAVA_ARGS="$JAVA_ARGS -XX:+UnlockExperimentalVMOptions"
JAVA_ARGS="$JAVA_ARGS -XX:+DisableExplicitGC"
JAVA_ARGS="$JAVA_ARGS -XX:+AlwaysPreTouch"
JAVA_ARGS="$JAVA_ARGS -XX:G1NewSizePercent=30"
JAVA_ARGS="$JAVA_ARGS -XX:G1MaxNewSizePercent=40"
JAVA_ARGS="$JAVA_ARGS -XX:G1HeapRegionSize=8M"
JAVA_ARGS="$JAVA_ARGS -XX:G1ReservePercent=20"
JAVA_ARGS="$JAVA_ARGS -XX:G1HeapWastePercent=5"
JAVA_ARGS="$JAVA_ARGS -XX:G1MixedGCCountTarget=4"
JAVA_ARGS="$JAVA_ARGS -XX:InitiatingHeapOccupancyPercent=15"
JAVA_ARGS="$JAVA_ARGS -XX:G1MixedGCLiveThresholdPercent=90"
JAVA_ARGS="$JAVA_ARGS -XX:G1RSetUpdatingPauseTimePercent=5"
JAVA_ARGS="$JAVA_ARGS -XX:SurvivorRatio=32"
JAVA_ARGS="$JAVA_ARGS -XX:+PerfDisableSharedMem"
JAVA_ARGS="$JAVA_ARGS -XX:MaxTenuringThreshold=1"
JAVA_ARGS="$JAVA_ARGS -Dusing.aikars.flags=https://mcflags.emc.gs"
JAVA_ARGS="$JAVA_ARGS -Daikars.new.flags=true"

# AOT cache for faster startup
if [ -f "Server/HytaleServer.aot" ]; then
    JAVA_ARGS="$JAVA_ARGS -XX:AOTCache=Server/HytaleServer.aot"
fi

# Server arguments
SERVER_ARGS="--assets $ASSETS_PATH"
SERVER_ARGS="$SERVER_ARGS --bind 0.0.0.0:$PORT"
SERVER_ARGS="$SERVER_ARGS --accept-early-plugins"

# Optional: Disable Sentry crash reporting during development
# SERVER_ARGS="$SERVER_ARGS --disable-sentry"

# Optional: Enable backups
# SERVER_ARGS="$SERVER_ARGS --backup --backup-dir backups --backup-frequency 30"

# Start server
echo "========================================="
echo "  Hytale Server"
echo "========================================="
echo "RAM: $MIN_RAM - $MAX_RAM"
echo "Port: $PORT (UDP)"
echo "Assets: $ASSETS_PATH"
echo ""

java $JAVA_ARGS -jar $SERVER_JAR $SERVER_ARGS
EOFSTART

# Replace placeholders
sed -i "s/__PORT__/$SERVER_PORT/g" start.sh
sed -i "s/__MIN_RAM__/$MIN_RAM/g" start.sh
sed -i "s/__MAX_RAM__/$MAX_RAM/g" start.sh

chmod +x start.sh
echo "✓ start.sh created"

# Create stop script
echo ""
echo "[6/7] Creating stop script..."

cat > stop.sh << 'EOFSTOP'
#!/bin/bash

# Send stop command to server console
if [ -f "server.pid" ]; then
    PID=$(cat server.pid)
    if ps -p $PID > /dev/null; then
        echo "Stopping server (PID: $PID)..."
        kill -SIGTERM $PID

        # Wait for graceful shutdown
        for i in {1..30}; do
            if ! ps -p $PID > /dev/null; then
                echo "Server stopped successfully"
                rm server.pid
                exit 0
            fi
            sleep 1
        done

        echo "Server did not stop gracefully. Force killing..."
        kill -9 $PID
        rm server.pid
    else
        echo "Server is not running (stale PID file)"
        rm server.pid
    fi
else
    echo "Server is not running (no PID file)"
fi
EOFSTOP

chmod +x stop.sh
echo "✓ stop.sh created"

# Create systemd service (optional)
echo ""
echo "[7/7] Create systemd service? (optional)"
read -p "Create systemd service for auto-start? (y/n): " CREATE_SERVICE

if [ "$CREATE_SERVICE" = "y" ]; then
    read -p "Enter service name (e.g., hytale): " SERVICE_NAME
    SERVICE_NAME=${SERVICE_NAME:-hytale}

    sudo cat > /etc/systemd/system/${SERVICE_NAME}.service << EOFSERVICE
[Unit]
Description=Hytale Server
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$SERVER_DIR
ExecStart=$SERVER_DIR/start.sh
ExecStop=$SERVER_DIR/stop.sh
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOFSERVICE

    sudo systemctl daemon-reload
    sudo systemctl enable ${SERVICE_NAME}.service

    echo "✓ Systemd service created: ${SERVICE_NAME}.service"
    echo ""
    echo "Start with: sudo systemctl start $SERVICE_NAME"
    echo "Stop with: sudo systemctl stop $SERVICE_NAME"
    echo "Status: sudo systemctl status $SERVICE_NAME"
    echo "Logs: sudo journalctl -u $SERVICE_NAME -f"
fi

# Summary
echo ""
echo "========================================="
echo "  Setup Complete!"
echo "========================================="
echo ""
echo "Server directory: $SERVER_DIR"
echo "Port: $SERVER_PORT (UDP)"
echo "RAM: $MIN_RAM - $MAX_RAM"
echo ""
echo "Next steps:"
echo "  1. Start server: ./start.sh"
echo "  2. Authenticate: /auth login device"
echo "  3. Visit https://accounts.hytale.com/device and enter code"
echo "  4. Install LumaGuilds: Download to mods/ folder"
echo "  5. Configure: Edit config.json after first launch"
echo ""
echo "Useful commands:"
echo "  Start: ./start.sh"
echo "  Stop: ./stop.sh"
echo "  Logs: tail -f logs/latest.log"
echo ""
echo "⚠ IMPORTANT:"
echo "  - Hytale uses UDP, not TCP!"
echo "  - Port $SERVER_PORT must be open for UDP traffic"
echo "  - First launch requires authentication"
echo "  - Maximum 100 servers per license"
echo ""
echo "Documentation: See HYTALE_SERVER_SETUP.md"
echo ""
