name: LumaGuilds
version: 0.4.0
api-version: '1.21'
main: net.lumalyte.lg.LumaGuilds
softdepend: [Vault, PlaceholderAPI]

commands:
  bellclaims:
    description: LumaGuilds administrative commands
    usage: /bellclaims <subcommand> [args]
    permission: bellclaims.admin